spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
gemini.api.key=${GEMINI_API_KEY}
   server.port=${PORT:8080}
